# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/box-share.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(261, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setSpacing(13)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelHijri = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Amiri")
        font.setPointSize(13)
        self.labelHijri.setFont(font)
        self.labelHijri.setText("")
        self.labelHijri.setObjectName("labelHijri")
        self.verticalLayout_3.addWidget(self.labelHijri)
        self.labelDate = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDate.setFont(font)
        self.labelDate.setText("")
        self.labelDate.setObjectName("labelDate")
        self.verticalLayout_3.addWidget(self.labelDate)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.lineEditSearch = QtWidgets.QLineEdit(self.frame)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(0, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditSearch.setFont(font)
        self.lineEditSearch.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditSearch.setClearButtonEnabled(True)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.verticalLayout_3.addWidget(self.lineEditSearch)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setContentsMargins(15, 5, 0, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonCode = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonCode.setFont(font)
        self.radioButtonCode.setChecked(True)
        self.radioButtonCode.setObjectName("radioButtonCode")
        self.verticalLayout.addWidget(self.radioButtonCode)
        self.radioButtonRef = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonRef.setFont(font)
        self.radioButtonRef.setObjectName("radioButtonRef")
        self.verticalLayout.addWidget(self.radioButtonRef)
        self.radioButtonDesig = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonDesig.setFont(font)
        self.radioButtonDesig.setObjectName("radioButtonDesig")
        self.verticalLayout.addWidget(self.radioButtonDesig)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.pushButtonSearch = QtWidgets.QPushButton(self.frame)
        self.pushButtonSearch.setMinimumSize(QtCore.QSize(0, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSearch.setFont(font)
        self.pushButtonSearch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonSearch.setAutoFillBackground(False)
        self.pushButtonSearch.setIconSize(QtCore.QSize(16, 15))
        self.pushButtonSearch.setAutoDefault(False)
        self.pushButtonSearch.setDefault(True)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.verticalLayout_3.addWidget(self.pushButtonSearch)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.toolButtonUser = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonUser.sizePolicy().hasHeightForWidth())
        self.toolButtonUser.setSizePolicy(sizePolicy)
        self.toolButtonUser.setMinimumSize(QtCore.QSize(0, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolButtonUser.setFont(font)
        self.toolButtonUser.setText("")
        self.toolButtonUser.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButtonUser.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonUser.setObjectName("toolButtonUser")
        self.verticalLayout_3.addWidget(self.toolButtonUser)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setMinimumSize(QtCore.QSize(271, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTitle.setFont(font)
        self.labelTitle.setText("")
        self.labelTitle.setIndent(5)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout.addWidget(self.labelTitle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.comboBoxCategory = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxCategory.setMinimumSize(QtCore.QSize(131, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxCategory.setFont(font)
        self.comboBoxCategory.setEditable(False)
        self.comboBoxCategory.setCurrentText("")
        self.comboBoxCategory.setObjectName("comboBoxCategory")
        self.horizontalLayout.addWidget(self.comboBoxCategory)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuStatistique = QtWidgets.QMenu(self.menubar)
        self.menuStatistique.setObjectName("menuStatistique")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(20, 20))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionStockAlarm = QtWidgets.QAction(MainWindow)
        self.actionStockAlarm.setObjectName("actionStockAlarm")
        self.actionArticleSansPrix = QtWidgets.QAction(MainWindow)
        self.actionArticleSansPrix.setObjectName("actionArticleSansPrix")
        self.actionArticleSansEmp = QtWidgets.QAction(MainWindow)
        self.actionArticleSansEmp.setObjectName("actionArticleSansEmp")
        self.actionTotalDesArticle = QtWidgets.QAction(MainWindow)
        self.actionTotalDesArticle.setObjectName("actionTotalDesArticle")
        self.actionHistoryMovement = QtWidgets.QAction(MainWindow)
        self.actionHistoryMovement.setObjectName("actionHistoryMovement")
        self.actionSaveAsExcel = QtWidgets.QAction(MainWindow)
        self.actionSaveAsExcel.setObjectName("actionSaveAsExcel")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionDel = QtWidgets.QAction(MainWindow)
        self.actionDel.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(10)
        self.actionDel.setFont(font)
        self.actionDel.setObjectName("actionDel")
        self.actionModify = QtWidgets.QAction(MainWindow)
        self.actionModify.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(10)
        self.actionModify.setFont(font)
        self.actionModify.setObjectName("actionModify")
        self.actionNewEntry = QtWidgets.QAction(MainWindow)
        self.actionNewEntry.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(10)
        self.actionNewEntry.setFont(font)
        self.actionNewEntry.setObjectName("actionNewEntry")
        self.actionNewSortie = QtWidgets.QAction(MainWindow)
        self.actionNewSortie.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(10)
        self.actionNewSortie.setFont(font)
        self.actionNewSortie.setObjectName("actionNewSortie")
        self.actionAddArticle = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(10)
        self.actionAddArticle.setFont(font)
        self.actionAddArticle.setObjectName("actionAddArticle")
        self.actionArtMov = QtWidgets.QAction(MainWindow)
        self.actionArtMov.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(10)
        self.actionArtMov.setFont(font)
        self.actionArtMov.setObjectName("actionArtMov")
        self.actionN_Category = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(10)
        self.actionN_Category.setFont(font)
        self.actionN_Category.setObjectName("actionN_Category")
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionHistoryMovement)
        self.menuMenu.addAction(self.actionSaveAsExcel)
        self.menuMenu.addAction(self.actionQuit)
        self.menuStatistique.addAction(self.actionStockAlarm)
        self.menuStatistique.addAction(self.actionArticleSansPrix)
        self.menuStatistique.addAction(self.actionArticleSansEmp)
        self.menuStatistique.addSeparator()
        self.menuStatistique.addAction(self.actionTotalDesArticle)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuStatistique.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionN_Category)
        self.toolBar.addAction(self.actionAddArticle)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNewEntry)
        self.toolBar.addAction(self.actionNewSortie)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionModify)
        self.toolBar.addAction(self.actionDel)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionArtMov)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Magasin UP4"))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "Search Article"))
        self.radioButtonCode.setText(_translate("MainWindow", "Code"))
        self.radioButtonRef.setText(_translate("MainWindow", "Reference"))
        self.radioButtonDesig.setText(_translate("MainWindow", "Designation"))
        self.pushButtonSearch.setText(_translate("MainWindow", "  Search"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Code"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Designation"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Reference"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Emp"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "U-M"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Qte"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Prix"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Valeur"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuStatistique.setTitle(_translate("MainWindow", "Statistique"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionStockAlarm.setText(_translate("MainWindow", "Stock Alam"))
        self.actionArticleSansPrix.setText(_translate("MainWindow", "Article Sans Prix"))
        self.actionArticleSansEmp.setText(_translate("MainWindow", "Article Sans Emplacement"))
        self.actionTotalDesArticle.setText(_translate("MainWindow", "Total Des Article"))
        self.actionHistoryMovement.setText(_translate("MainWindow", "History Des Movement"))
        self.actionSaveAsExcel.setText(_translate("MainWindow", "Save As Excel File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionDel.setText(_translate("MainWindow", "Supprimer"))
        self.actionDel.setToolTip(_translate("MainWindow", "Supprimer l\'article."))
        self.actionModify.setText(_translate("MainWindow", "Modifier"))
        self.actionModify.setToolTip(_translate("MainWindow", "Modifier L\'Article"))
        self.actionNewEntry.setText(_translate("MainWindow", "Entree"))
        self.actionNewSortie.setText(_translate("MainWindow", "Sortie"))
        self.actionAddArticle.setText(_translate("MainWindow", "N.Article"))
        self.actionAddArticle.setToolTip(_translate("MainWindow", "Nouvoueau Article"))
        self.actionArtMov.setText(_translate("MainWindow", "Movement"))
        self.actionArtMov.setToolTip(_translate("MainWindow", "Article Movement"))
        self.actionN_Category.setText(_translate("MainWindow", "N.Category"))
        self.actionN_Category.setToolTip(_translate("MainWindow", "Nouvelle Category"))

