# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\movement.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowMovement(object):
    def setupUi(self, MainWindowMovement):
        MainWindowMovement.setObjectName("MainWindowMovement")
        MainWindowMovement.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(11)
        MainWindowMovement.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindowMovement)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditSearchMov = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSearchMov.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditSearchMov.setObjectName("lineEditSearchMov")
        self.horizontalLayout.addWidget(self.lineEditSearchMov)
        self.comboBoxOperation = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxOperation.setMinimumSize(QtCore.QSize(94, 35))
        self.comboBoxOperation.setObjectName("comboBoxOperation")
        self.comboBoxOperation.addItem("")
        self.comboBoxOperation.addItem("")
        self.comboBoxOperation.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxOperation)
        self.dateEditMov = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditMov.setMinimumSize(QtCore.QSize(0, 35))
        self.dateEditMov.setCalendarPopup(True)
        self.dateEditMov.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEditMov.setObjectName("dateEditMov")
        self.horizontalLayout.addWidget(self.dateEditMov)
        self.pushButtonSearchMov = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSearchMov.setMinimumSize(QtCore.QSize(94, 35))
        self.pushButtonSearchMov.setObjectName("pushButtonSearchMov")
        self.horizontalLayout.addWidget(self.pushButtonSearchMov)
        self.pushButtonMovRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMovRefresh.setMinimumSize(QtCore.QSize(94, 35))
        self.pushButtonMovRefresh.setObjectName("pushButtonMovRefresh")
        self.horizontalLayout.addWidget(self.pushButtonMovRefresh)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindowMovement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowMovement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuEtats = QtWidgets.QMenu(self.menubar)
        self.menuEtats.setObjectName("menuEtats")
        MainWindowMovement.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowMovement)
        self.statusbar.setObjectName("statusbar")
        MainWindowMovement.setStatusBar(self.statusbar)
        self.actionJournalier = QtWidgets.QAction(MainWindowMovement)
        self.actionJournalier.setObjectName("actionJournalier")
        self.actionMensuel = QtWidgets.QAction(MainWindowMovement)
        self.actionMensuel.setObjectName("actionMensuel")
        self.actionTous = QtWidgets.QAction(MainWindowMovement)
        self.actionTous.setObjectName("actionTous")
        self.menuEtats.addAction(self.actionJournalier)
        self.menuEtats.addAction(self.actionMensuel)
        self.menuEtats.addAction(self.actionTous)
        self.menubar.addAction(self.menuEtats.menuAction())

        self.retranslateUi(MainWindowMovement)
        QtCore.QMetaObject.connectSlotsByName(MainWindowMovement)

    def retranslateUi(self, MainWindowMovement):
        _translate = QtCore.QCoreApplication.translate
        MainWindowMovement.setWindowTitle(_translate("MainWindowMovement", "Magasin Movement"))
        self.lineEditSearchMov.setPlaceholderText(_translate("MainWindowMovement", "Code Article"))
        self.comboBoxOperation.setItemText(0, _translate("MainWindowMovement", "Tous"))
        self.comboBoxOperation.setItemText(1, _translate("MainWindowMovement", "Entree"))
        self.comboBoxOperation.setItemText(2, _translate("MainWindowMovement", "Sortie"))
        self.pushButtonSearchMov.setText(_translate("MainWindowMovement", "Search"))
        self.pushButtonMovRefresh.setText(_translate("MainWindowMovement", "Refresh"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowMovement", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowMovement", "User"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowMovement", "Operation"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowMovement", "Code"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowMovement", "Designation"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindowMovement", "Qte"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindowMovement", "Prix"))
        self.menuEtats.setTitle(_translate("MainWindowMovement", "Etats"))
        self.actionJournalier.setText(_translate("MainWindowMovement", "Journalier"))
        self.actionMensuel.setText(_translate("MainWindowMovement", "Mensuel"))
        self.actionTous.setText(_translate("MainWindowMovement", "Tous"))

