# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\new_article.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_newArticle(object):
    def setupUi(self, newArticle):
        newArticle.setObjectName("newArticle")
        newArticle.resize(552, 587)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        newArticle.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        newArticle.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(newArticle)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(newArticle)
        self.label_8.setMinimumSize(QtCore.QSize(0, 84))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(newArticle)
        self.label_9.setMinimumSize(QtCore.QSize(125, 31))
        self.label_9.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.comboBoxCategory = QtWidgets.QComboBox(newArticle)
        self.comboBoxCategory.setMinimumSize(QtCore.QSize(0, 31))
        self.comboBoxCategory.setObjectName("comboBoxCategory")
        self.horizontalLayout_9.addWidget(self.comboBoxCategory)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(newArticle)
        self.label.setMinimumSize(QtCore.QSize(125, 31))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditCode = QtWidgets.QLineEdit(newArticle)
        self.lineEditCode.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEditCode.setStyleSheet("selection-color: rgb(255, 0, 0);")
        self.lineEditCode.setFrame(True)
        self.lineEditCode.setObjectName("lineEditCode")
        self.horizontalLayout.addWidget(self.lineEditCode)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(newArticle)
        self.label_2.setMinimumSize(QtCore.QSize(125, 31))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditDesig = QtWidgets.QLineEdit(newArticle)
        self.lineEditDesig.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEditDesig.setObjectName("lineEditDesig")
        self.horizontalLayout_2.addWidget(self.lineEditDesig)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(newArticle)
        self.label_3.setMinimumSize(QtCore.QSize(125, 31))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEditRef = QtWidgets.QLineEdit(newArticle)
        self.lineEditRef.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEditRef.setObjectName("lineEditRef")
        self.horizontalLayout_3.addWidget(self.lineEditRef)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(newArticle)
        self.label_4.setMinimumSize(QtCore.QSize(125, 31))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEditUM = QtWidgets.QLineEdit(newArticle)
        self.lineEditUM.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEditUM.setObjectName("lineEditUM")
        self.horizontalLayout_4.addWidget(self.lineEditUM)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(newArticle)
        self.label_5.setMinimumSize(QtCore.QSize(125, 31))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEditEmp = QtWidgets.QLineEdit(newArticle)
        self.lineEditEmp.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEditEmp.setObjectName("lineEditEmp")
        self.horizontalLayout_5.addWidget(self.lineEditEmp)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(newArticle)
        self.label_6.setMinimumSize(QtCore.QSize(125, 31))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.spinBoxQte = QtWidgets.QSpinBox(newArticle)
        self.spinBoxQte.setMinimumSize(QtCore.QSize(399, 31))
        self.spinBoxQte.setMinimum(1)
        self.spinBoxQte.setMaximum(10000)
        self.spinBoxQte.setObjectName("spinBoxQte")
        self.horizontalLayout_6.addWidget(self.spinBoxQte)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(newArticle)
        self.label_7.setMinimumSize(QtCore.QSize(125, 31))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.doubleSpinBoxPrix = QtWidgets.QDoubleSpinBox(newArticle)
        self.doubleSpinBoxPrix.setMinimumSize(QtCore.QSize(399, 31))
        self.doubleSpinBoxPrix.setProperty("showGroupSeparator", False)
        self.doubleSpinBoxPrix.setDecimals(3)
        self.doubleSpinBoxPrix.setMaximum(100000000000000.0)
        self.doubleSpinBoxPrix.setObjectName("doubleSpinBoxPrix")
        self.horizontalLayout_7.addWidget(self.doubleSpinBoxPrix)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(newArticle)
        self.label_10.setMinimumSize(QtCore.QSize(125, 31))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.lineEditObs = QtWidgets.QLineEdit(newArticle)
        self.lineEditObs.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEditObs.setObjectName("lineEditObs")
        self.horizontalLayout_11.addWidget(self.lineEditObs)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.labelError = QtWidgets.QLabel(newArticle)
        self.labelError.setMinimumSize(QtCore.QSize(398, 0))
        self.labelError.setStyleSheet("color: rgb(239, 41, 41);")
        self.labelError.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelError.setText("")
        self.labelError.setWordWrap(True)
        self.labelError.setObjectName("labelError")
        self.horizontalLayout_10.addWidget(self.labelError)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.pushButtonClose = QtWidgets.QPushButton(newArticle)
        self.pushButtonClose.setMinimumSize(QtCore.QSize(102, 37))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayout_8.addWidget(self.pushButtonClose)
        self.pushButtonAdd = QtWidgets.QPushButton(newArticle)
        self.pushButtonAdd.setEnabled(True)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(140, 37))
        self.pushButtonAdd.setDefault(True)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout_8.addWidget(self.pushButtonAdd)
        self.verticalLayout.addLayout(self.horizontalLayout_8)

        self.retranslateUi(newArticle)
        self.pushButtonClose.clicked.connect(newArticle.close)
        QtCore.QMetaObject.connectSlotsByName(newArticle)

    def retranslateUi(self, newArticle):
        _translate = QtCore.QCoreApplication.translate
        newArticle.setWindowTitle(_translate("newArticle", "New Article"))
        self.label_8.setText(_translate("newArticle", "Nouveaux Article"))
        self.label_9.setText(_translate("newArticle", "Category"))
        self.label.setText(_translate("newArticle", "Code"))
        self.label_2.setText(_translate("newArticle", "Designation"))
        self.label_3.setText(_translate("newArticle", "Reference"))
        self.label_4.setText(_translate("newArticle", "U Mesure"))
        self.label_5.setText(_translate("newArticle", "Emplacement"))
        self.label_6.setText(_translate("newArticle", "Quantite"))
        self.label_7.setText(_translate("newArticle", "Prix"))
        self.label_10.setText(_translate("newArticle", "Observation"))
        self.pushButtonClose.setText(_translate("newArticle", "Annuler"))
        self.pushButtonAdd.setText(_translate("newArticle", "Add Article"))

